### PR TITLE
Adds OnShape instructions

### PR DESCRIPTION
**Pull request by tcr**
I tried this, it worked, let's document it.

### CODE REVIEW

**Comment by kevinmehall** [comment]
Can there be a link?

**Comment by tcr** [comment]
No, there's no direct link you can copy.

**Comment by kevinmehall** [comment]
Does https://cad.onshape.com/documents/50a5c011c1d44d7ca5c90fbf work for you?

**Comment by tcr** [comment]
It does! Updated.

**Comment by ekolker** [comment]
lgtm. merging.

**Pull request merged**
